/*

 DROPLET_LEVEL_MENU_BG.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DropletBackgroundLevelMenuWidth 20
#define DropletBackgroundLevelMenuHeight 18
#define DropletBackgroundLevelMenuBank 0

extern unsigned char DropletBackgroundLevelMenu[];

/* End of DROPLET_LEVEL_MENU_BG.H */
