/*

 DROPLET_SPLASH_BG.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DropletSplashBackgroundWidth 20
#define DropletSplashBackgroundHeight 18
#define DropletSplashBackgroundBank 0

extern unsigned char DropletSplashBackground[];

/* End of DROPLET_SPLASH_BG.H */
