/*

 DROPLET_LEVEL2_BG.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DropletBackgroundLevel2Width 20
#define DropletBackgroundLevel2Height 18
#define DropletBackgroundLevel2Bank 0

extern unsigned char DropletBackgroundLevel2[];

/* End of DROPLET_LEVEL2_BG.H */
