/*

 DROPLET_LEVEL3_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\apadi\Documents\projects\gameboy\droplet\data\tiles\droplet_background_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DropletBackgroundLevel3Width 20
#define DropletBackgroundLevel3Height 18
#define DropletBackgroundLevel3Bank 0

extern unsigned char DropletBackgroundLevel3[];

/* End of DROPLET_LEVEL3_BG.H */
