/*

 DROPLET_LEVEL1_BG.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DropletBackgroundLevel1Width 20
#define DropletBackgroundLevel1Height 18
#define DropletBackgroundLevel1Bank 0

extern unsigned char DropletBackgroundLevel1[];

/* End of DROPLET_LEVEL1_BG.H */
